### PR TITLE
Remove requirement patch for default_pricing_plan_id

### PR DESCRIPTION
**Pull request by testower**
Solves #71

### CODE REVIEW

**Review by PierrickP — APPROVED** [review]

**Comment by testower** [comment]
Ok I found I had to remove a test condition as well, but should be all good now.

**Comment by PierrickP** [comment]
@testower oups, i didn't checked the result of netlify. I don't know why it so verbose on this repository ..

**Comment by PierrickP** [comment]
> 4:16:46 PM: Build exceeded maximum allowed runtime
but doesn't mind there are a problem with the current code :\

**Comment by testower** [comment]
Yes seems like ajv is having issue parsing the schema, even v2.2 now. I'm trying to figure out what's going on.

**Comment by PierrickP** [comment]
I just checked locally with your branch, i don't have any error on unit test and manually with a feed (v2.2).
Try to remove your node_module and run `yarn` one more time

**Comment by testower** [comment]
Yeah I am having trouble even with master branch. Unit tests are ok though

**Comment by PierrickP** [comment]
Can you share with me the feed are you testing with ? (here / mobilitydata slack or my email firstname.lastname@fluctuo.com)

**Comment by testower** [comment]
Any feed. I Get error from jab: Error compiling schema. I will try to reset everything

**Comment by testower** [comment]
Seems like everything is A-OK on my side now as well. Unrelated problems. What's up with alle the netlify failures?

**Comment by isabelle-dr** [comment]
I'm not sure... 🤔
Are we OK to merge this PR?

**Comment by testower** [comment]
I think it is ok. I don’t know what’s up with the Netlify messages.

**Pull request merged**
