### PR TITLE
Update Json Schema

### LINKED ISSUE #65: Update schemas
To reflect the recent changes (https://github.com/MobilityData/gbfs-json-schema/pull/66)

### PR DESCRIPTION
**Pull request by isabelle-dr**
Closes #65 
This change includes:
- The replacement of the[ v2.3RC](https://github.com/NABSA/gbfs/blob/v2.3-RC/gbfs.md) with the [v2.3-RC2](https://github.com/NABSA/gbfs/blob/v2.3-RC2/gbfs.md) done in [MobilityData/gbfs-json-schema/pull/67](https://github.com/MobilityData/gbfs-json-schema/pull/67)
- The fixes done in [MobilityData/gbfs-json-schema/pull/66](https://github.com/MobilityData/gbfs-json-schema/pull/66)

### CODE REVIEW

**Comment by testower** [comment]
@isabelle-dr I believe you have a unit test failing because it's trying to read the schema from the wrong path due to this fixture: 

https://github.com/MobilityData/gbfs-validator/blob/master/gbfs-validator/__test__/fixtures/plan_id.js#L10

Change the version on this line to '2.3-RC2' and I think it will pass again.

**Review by testower — APPROVED** [review]
Looks good, apart from the failing unit test, which should be easy to fix 👍

**Comment by isabelle-dr** [comment]
@PierrickP Still failing 😕 I can't seem to find why. 
Also: I renamed the folder in the schemas V2.3-RC2, do you think this would cause an issue with the version drop-down on the website?

**Comment by isabelle-dr** [comment]
Well it seems like it does 🙈. I updated the `Validator.vue` file to match the new name. I still can't get why the unit tests are failing.

**Review by testower — CHANGES_REQUESTED** [review]
Actually, I think we need to hold this up. There is a breaking change in vehicle_types.json here, which is the requirement of default_pricing_plan_id. Mitch was going to look into it. Meanwhile, I'm having a look at the tests.

**Comment by testower** [comment]
Here is a PR into this branch that fixes the issue: https://github.com/MobilityData/gbfs-validator/pull/68

I still think we need to remove the requirement condition on default_pricing_plan_id though.

**Comment by PierrickP** [comment]
Thanks @testower, i merged your PR to fix this PR.

@isabelle-dr you renamed RC to RC2. Should we NOT keep old RCs ?

**Comment by PierrickP** [comment]
@isabelle-dr Thanks
Ok for the v2-3-RC and i ll make a PR to update the version requirement according to the latest change

**Pull request merged**
